name: Docker Image

on:
  pull_request:

jobs:
  tests:
    name: Build Docker Image
    runs-on: ubuntu-20.04

    steps:
      - name: Checkout Code
        uses: actions/checkout@v2

      - name: Docker build
        run: docker build .

# vim:ft=yaml:et:ts=2:sw=2
