name: Lint

on:
  pull_request:

jobs:
  tests:
    name: PHP CS Fixer
    runs-on: ubuntu-20.04

    steps:
      - name: Checkout Code
        uses: actions/checkout@v2

      - name: Setup PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: 7.2
          tools: php-cs-fixer:2.16
          coverage: none

      - name: Install dependencies with composer
        run: composer install --no-interaction --no-progress --no-suggest

      - name: Run php-cs-fixer
        run: php-cs-fixer fix -vvv

# vim:ft=yaml:et:ts=2:sw=2
